basePath: /v1/ec2
host: localhost:8080
info:
  contact: {}
  description: This API is used to manager aws ec2.
  title: Manage EC2 API
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: Cretae a rc2 instance
      parameters:
      - description: user name
        in: query
        name: username
        required: true
        type: string
      - description: instance image id
        in: query
        name: imageId
        type: string
      - description: instance type
        in: query
        name: instanceType
        type: string
      - description: instance diskSize
        in: query
        name: diskSize
        type: integer
      - description: user department
        in: query
        name: department
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Create a ec2 instance
      tags:
      - Instance
  /key:
    post:
      consumes:
      - application/json
      description: Cretae a rsa keyPair for the user.
      parameters:
      - description: user name
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Create a keyPair
      tags:
      - Instance
  /start:
    post:
      consumes:
      - application/json
      description: Start a EC2 Instance.
      parameters:
      - description: instance Id
        in: query
        name: instanceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Start a EC2 Instance
      tags:
      - Instance
  /stop:
    post:
      consumes:
      - application/json
      description: Stop a EC2 Instance.
      parameters:
      - description: instance Id
        in: query
        name: instanceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Stop a EC2 Instance
      tags:
      - Instance
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
